import "../globals.css";
import type { Metadata } from "next";

import { dir } from "i18next";
import { languages } from "../i18n/settings";

import GlobalContextProvider from "../globalContext";

export async function generateStaticPaths() {
    return languages.map((lng) => ({
        params: { lng },
    }));
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export type RootLayoutParams = {
    lng: string;
};

export default function RootLayout({
    children,
    params,
}: {
    children: React.ReactNode;
    params: RootLayoutParams;
}) {
    return (
        <html lang={params.lng} dir={dir(params.lng)}>
            <body>
                <GlobalContextProvider lng={params.lng}>
                    {children}
                </GlobalContextProvider>
            </body>
        </html>
    );
}
